### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/sioyek#1]
Hi @raffaem, we need to adjust a few things first to move forward, ok? ✨

We need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by raffaelemancuso** [comment]
I cannot push here ... is it correlated with the fact that the repository has only read access in the team?

![image](https://user-images.githubusercontent.com/54762742/196757146-5df3ca8c-5c7d-4df1-8886-d6baa1e8594f.png)

**Comment by luxonauta** [comment]
My mistake; try again now! 😅
